version: '3'

services:
   ###elasticsearch###
  Elasticsearch:
    image: elasticsearch:7.17.0
    container_name: Elasticsearch
    ports:
      - '9200:9200'
      - '22:22'
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - api-note-elasticStack
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:        
    - ./elasticData:/usr/share/elasticsearch/data
  
  kibana:
    image: kibana:7.17.0
    container_name: kibana
    depends_on:
      - Elasticsearch
    environment:
     - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    networks:
      - api-note-elasticStack
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./kibana:/usr/share/kibana/data
    ports:
      - '5601:5601'
networks:
  api-note-elasticStack:
    driver: bridge